---
abstract: 'Dist::Zilla plugin bundle for the HTGT team'
author:
  - 'Ray Miller'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-HTGT
requires:
  Dist::Zilla: 0
  Dist::Zilla::Plugin::Git: 0
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Plugin::NoSmartCommentsTests: 0
  Dist::Zilla::Plugin::PerlTidy: 0
  Dist::Zilla::Plugin::Test::EOL: 0
  Dist::Zilla::Plugin::Test::Perl::Critic: 0
  Dist::Zilla::Role::FileFinderUser: 0
  Dist::Zilla::Role::FileMunger: 0
  Dist::Zilla::Role::PPI: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  MooseX::Types::Perl: 0
  PPI: 0
  Test::NoSmartComments: 0
  Test::Perl::Critic: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
version: 0.009
